Feature/delete project
eduskx/hammerhart pull request #35
Opened 2024-08-05 10:00 UTC by SukranSari

2024-08-05 13:55 UTC, NikRoe requested changes
Hi there,

a promising start!

I left some notes with the help of which you can improve the reusability of your modal and get rid of some props that you don't need.

Keep it up 🙌

2024-08-05 13:55 UTC, NikRoe commented on components/Modal/ModalContent.js
> +  const router = useRouter();
```suggestion
```

2024-08-05 13:55 UTC, NikRoe commented on components/Modal/ModalContent.js
> +import { useRouter } from "next/router";
```suggestion
```

2024-08-06 12:26 UTC, eduskx commented on pages/_app.js
>  const saira = Saira({ subsets: ["latin"] });
Thanks for the hint! We will consider this in a future user story.

2024-08-06 15:35 UTC, merged