add searchbar component, functionality and styling
eduskx/hammerhart pull request #44
Opened 2024-08-07 14:14 UTC by eduskx

Thank you very much for having a look 🫶🏻

2024-08-07 15:45 UTC, NikRoe requested changes
Hi team,

nicely done 🙌 

However, I recommend working with a helper function to set the searchInput state and write this function in the same file where your state lives.

This is in general a good approach for several reasons:

1. Better Control Over Logic
By writing helper functions, you can centralize and control the logic executed when the state changes. This allows you to add additional validations, transformations, or other logical operations before the state is actually changed.

2. Avoiding Errors
Directly passing the setter function can lead to unintended and hard-to-debug errors when the state is modified from multiple places. Helper functions ensure that the state is changed in a predictable and controlled manner.

3. Increased Readability and Maintainability
Helper functions increase the readability and maintainability of the code because they perform clearly named and specific tasks. This makes it easier for other developers (and for yourself in the future) to understand and extend the code.

4. Encapsulation of State Logic
Helper functions enable you to separate state logic from UI logic. This leads to better encapsulation and more modular code, which is easier to test and maintain.

5. Reusability
Helper functions can be reused if they are well-abstracted and generalized. This reduces redundancy and promotes consistency within the application.

Long story short: By implementing my suggestions, your app should still work just as fine as before, while having all of the above benefits 🙏

2024-08-07 15:45 UTC, NikRoe commented on components/SearchBar/index.js
> +  }
I would move this function one level higher.

In general it is a good practice to keep the setter functions of a state close to where you initialize the state.
It keeps your code cleaner and also easier to maintain.

My suggestion has a few adaptations as its consequence:

```suggestion

```

2024-08-07 15:45 UTC, NikRoe commented on components/SearchBar/index.js
> +export default function SearchBar({ setSearchInput }) {
```suggestion
export default function SearchBar({ onSearch }) {

```

2024-08-07 15:45 UTC, NikRoe commented on components/SearchBar/index.js
> +        onChange={inputHandler}
```suggestion
        onChange={onSearch}

```

2024-08-07 15:45 UTC, NikRoe commented on pages/index.js
> +      <SearchBar setSearchInput={setSearchInput} />
```suggestion
      <SearchBar onSearch={handleSearch} />
```

2024-08-07 15:45 UTC, NikRoe commented on pages/index.js
> +
```suggestion
function handleSearch(event) {
    const lowerCasedInput = event.target.value.toLowerCase();
    setSearchInput(lowerCasedInput);
  }
```

2024-08-08 09:23 UTC, eduskx commented
Thank you for this detailed explanation! Our team loves your reviews :)

2024-08-08 09:33 UTC, NikRoe approved these changes
LGTM

2024-08-08 10:01 UTC, merged